### ISSUE TITLE
Weight axis of VF has curious range

### ISSUE THREAD

**Issue by rsheeter** [Omnibus-Type/Saira#10]
What's up with weight [35, 243]?

```shell
ttx -t fvar -o - Saira.ttf | head -25

    <!-- Weight -->
    <Axis>
      <AxisTag>wght</AxisTag>
      <Flags>0x0</Flags>
      <MinValue>35.0</MinValue>
      <DefaultValue>116.0</DefaultValue>
      <MaxValue>243.0</MaxValue>
      <AxisNameID>256</AxisNameID>
    </Axis>

    <!-- Width -->
    <Axis>
      <AxisTag>wdth</AxisTag>
      <Flags>0x0</Flags>
      <MinValue>100.0</MinValue>
      <DefaultValue>500.0</DefaultValue>
      <MaxValue>700.0</MaxValue>
      <AxisNameID>257</AxisNameID>
    </Axis>
```

**Comment by rsheeter** [comment]
wght now looks OK but wdth seems a bit odd, assuming the intended widths more or less map onto the typical range I would expect something closer to [50, 200]

```xml
    <!-- Weight -->
    <Axis>
      <AxisTag>wght</AxisTag>
      <Flags>0x0</Flags>
      <MinValue>100.0</MinValue>
      <DefaultValue>400.0</DefaultValue>
      <MaxValue>900.0</MaxValue>
      <AxisNameID>256</AxisNameID>
    </Axis>

    <!-- Width -->
    <Axis>
      <AxisTag>wdth</AxisTag>
      <Flags>0x0</Flags>
      <MinValue>100.0</MinValue>
      <DefaultValue>500.0</DefaultValue>
      <MaxValue>700.0</MaxValue>
      <AxisNameID>257</AxisNameID>
    </Axis>
```

**Comment by davelab6** [comment]
> What's up with weight [35, 243]?

Those are the XOPQ values, the stem widths in per mille of em. 

> wdth seems a bit odd

Agree, width of 100/500/700 is incorrect, it should be 50/100/200 or 25/100/300 or so; https://docs.microsoft.com/en-us/typography/opentype/spec/os2#uswidthclass may be helpful. 

@dberlow do you have any tips on how to measure OS2 Width values?

**Comment by rsheeter** [comment]
At time of writing we don't support width outside the 50-200 range (though that isn't set in stone)

**Comment by dberlow** [comment]
The os/2 width default must be 100, and the range can either be 
a % from a measured value also measured in the default, or it can be
a value assigned relative to the default without any measure.

A measured value and actual % allows a program, or user, to equate an os/2 width value with a line length, and e.g. set the same text at 75% wdth in a column 75% narrower than a column width used with the font at 100% width. 

A fuller range than 80-100 was really only useful in a small number of families that condensed as far as 25%. But typically a family started out with a regular condensed for stylistic reasons or use at large sizes, and from there the narrower styles are measured 75-80% from the condensed default.

So, variables are really where we now can have a fuller range in on family, and from 25-100% is useful. Expanding most families to 200% might seem excessive. I had to stop expanding both Amstelvar and Extremo at 125% and 151% respectively, but I can imagine square Latin designs or other scripts that could go as wide as a measured 200% of the regular.

> On Mar 13, 2020, at 1:25 PM, Dave Crossland <notifications@github.com> wrote:
> 

﻿
What's up with weight [35, 243]?

Those are the XOPQ values, the stem widths in per mille of em.

wdth seems a bit odd

Agree, width of 100/500/700 is incorrect, it should be 50/100/200 or 25/100/300 or so; https://docs.microsoft.com/en-us/typography/opentype/spec/os2#uswidthclass may be helpful.

@dberlow do you have any tips on how to measure OS2 Width values?

**Comment by Omnibus-Type** [comment]
We map the wdth ranges between [50, 125], give a checkup and let us know what you think.

**Comment by rsheeter** [comment]
Looks good to me, ty.

```xml
    <!-- Weight -->
    <Axis>
      <AxisTag>wght</AxisTag>
      <Flags>0x0</Flags>
      <MinValue>100.0</MinValue>
      <DefaultValue>400.0</DefaultValue>
      <MaxValue>900.0</MaxValue>
      <AxisNameID>256</AxisNameID>
    </Axis>

    <!-- Width -->
    <Axis>
      <AxisTag>wdth</AxisTag>
      <Flags>0x0</Flags>
      <MinValue>50.0</MinValue>
      <DefaultValue>100.0</DefaultValue>
      <MaxValue>125.0</MaxValue>
      <AxisNameID>257</AxisNameID>
    </Axis>
```
