### ISSUE TITLE
google/fonts production quality assurance

### ISSUE THREAD

**Issue by graphicore** [Omnibus-Type/Saira#11]
Hi, I started the onboarding for the new version of Saira. Our QA tools found some issues that we need to address. You can see the report here: https://github.com/google/fonts/pull/2539

Beyond the Font Bakery report, I also think the Diffbrowsers report in [qa.zip](http://35.238.63.0/media/d54efbd2-c754-4b1f-8e74-1e4c52e746c1/qa.zip) reveals some issues.

Let me know how  you want to proceed.

**Comment by Omnibus-Type** [comment]
Hi @graphicore. We'll review the report and work on it. Greetings!
