### ISSUE TITLE
Weight regression

### ISSUE THREAD

**Issue by RosaWagner** [Omnibus-Type/Saira#12]
I am almost done with Saira. BUT when I thought I could send it, I noticed regression which usually upset users.
To avoid this, I would like to add an axis mapping to find the previous weight value of Regular and other instances. Do you agree?

![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/12222436/99814418-3fec7480-2b49-11eb-9c99-a97a3135981a.gif)

**Comment by Omnibus-Type** [comment]
Hi @RosaWagner We tried to affect the user as little as possible, but we had to touch some values to be able to move forward with the project. Could it be that you are working on an older version? I think if it is the latest version there would be no problem adding an axis mapping.

**Comment by RosaWagner** [comment]
I am working with the master of this repository so I think it's the last version, yes. I compared the stem thickness between Google's version and this one, we have 86 against 105 units. So if you are ok, I'll proceed with the axis mapping ;) 

I also re-structured the repository to have a more clear view and which sources is related to which statics.

**Comment by Omnibus-Type** [comment]
Yes Rosa, we agree with the axis mapping. It seems good to us that you have restructured according to how it has been done with the rest of the repositories, many thanks for the great work!
