### ISSUE TITLE
[Saira Stencil] v1.000 GF QA

### ISSUE THREAD

**Issue by m4rc1e** [Omnibus-Type/Saira#2]
## Fontbakery report

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Check font has a license.</summary>

* [com.google.fonts/check/028](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/028)
* **FAIL** [:fire:] No license file was found. Please add an OFL.txt or a LICENSE.txt file. If you are running fontbakery on a Google Fonts upstream repo, which is fine, just make sure there is a temporary license file in the same folder. [code: none]

</details>
<br>
</details>
<details>
<summary><b>[4] SairaStencil.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Checking file is named canonically.</summary>

* [com.google.fonts/check/001](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/001)
* **FAIL** [:fire:] Style name used in "/Users/marc/Documents/googlefonts/manual_font_cleaning/Saira/SairaStencil/fonts/ttf/SairaStencil.ttf" is not canonical. You should rebuild the font using any of the following style names: "Thin", "ExtraLight", "Light", "Regular", "Medium", "SemiBold", "Bold", "ExtraBold", "Black", "Thin Italic", "ExtraLight Italic", "Light Italic", "Italic", "Medium Italic", "SemiBold Italic", "Bold Italic", "ExtraBold Italic", "Black Italic".

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking with Microsoft Font Validator.</summary>

* [com.google.fonts/check/037](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/037)
* **FAIL** [:fire:] MS-FonVal: The xAvgCharWidth field does not equal the calculated value DETAILS: actual = 559, calc = 476
* **FAIL** [:fire:] MS-FonVal: There are undefined bits set in fsSelection field DETAILS: Bit(s) 7

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 Metrics match hhea Metrics.</summary>

* [com.google.fonts/check/042](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/042)
* **FAIL** [:fire:] OS/2 sTypoAscender and hhea ascent must be equal. [code: ascender]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Does full font name begin with the font family name?</summary>

* [com.google.fonts/check/068](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/068)
* **FAIL** [:fire:]  On the 'name' table, the full font name (NameID 4 - FULL_FONT_NAME: 'Saira Stencil') does not begin with font family name (NameID 1 - FONT_FAMILY_NAME: 'SairaStencil') [code: does-not]

</details>
<br>
</details>

### Summary

| :broken_heart: ERROR | :fire: FAIL | :warning: WARN | :zzz: SKIP | :information_source: INFO | :croissant: PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 5 | 7 | 66 | 5 | 49 |
| 0% | 4% | 5% | 50% | 4% | 37% |

**Note:** The following loglevels were omitted in this report:
* **WARN**
* **SKIP**
* **INFO**
* **PASS**

Ignore the license issue and ms validator issues. We'll solve this when uploading to google/fonts

Double check you're happy with the glyphs.

![desktop_windows_7_ie_9 0_](https://user-images.githubusercontent.com/7525512/40234558-355a127a-5a9f-11e8-8be6-1db2885fdd59.jpg)

**Comment by Yorlmar** [comment]
• Check the names
• I'm confused about OS2/2 Metrics because I use the method to calculate the dimensions developed by karsten lücke and then I round the final values.
http://kltf.de/downloads/FontMetrics-kltf.pdf
Also I adopt the Microsoft Strategy from the Glyphs tutorials
https://glyphsapp.com/tutorials/vertical-metrics
