### ISSUE TITLE
Rename Saira Stencil to Saira Stencil One

### ISSUE THREAD

**Issue by m4rc1e** [Omnibus-Type/Saira#7]
We recently tried to push Saira Stencil https://github.com/google/fonts/pull/1693. It was rejected because of the family name. Since the family consists of a single style which is not a Regular weight, we want the family to be renamed to Saira Stencil One.

If you [search for "One" families on fonts.google.com](https://fonts.google.com/?query=one). You will see they are all single weight families that have a Regular style which isn't a true regular.

Once the family name has been updated, I will repush the family to google/fonts.

cc @davelab6

**Comment by Omnibus-Type** [comment]
Done! Thanks @m4rc1e <3
